Fixing lua header mismatch
Cloning into 'oxwm'...
done.
==> Starting pkgver()...
==> Updated version: oxwm-git 0.11.3.10.gf72f06d-1
==> Sources are ready.
==> Making package: oxwm-git 0.11.3.10.gf72f06d-1 (Tue 24 Mar 2026 04:43:15 AM EDT)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Starting pkgver()...
==> Starting build()...
==> Starting check()...
test
└─ run test
   └─ compile test ReleaseSmall native 1 errors
error: undefined symbol: luaL_openselectedlibs
    note: referenced by .zig-cache/o/747b51bcc23a666b914d361583a70c6c/test_zcu.o:.text
error: the following command failed with 1 compilation errors:
/usr/bin/zig test -fno-lld .zig-cache/o/3f099549888438d13cdc867461e07421/liblua.a -OReleaseSmall -I .zig-cache/o/53ed955ced3c0fd35a0b9feb57db3332 --dep lua -Mroot=/home/dwilliams/.cache/yay/oxwm-git/src/oxwm/tests/lua_config_tests.zig -OReleaseSmall -Mlua=/home/dwilliams/.cache/yay/oxwm-git/src/oxwm/src/config/lua.zig -lc --cache-dir .zig-cache --global-cache-dir /home/dwilliams/.cache/zig --name test --zig-lib-dir /usr/lib/zig/ --listen=-

Build Summary: 6/9 steps succeeded; 1 failed; 15/15 tests passed
test transitive failure
└─ run test transitive failure
   └─ compile test ReleaseSmall native 1 errors

error: the following build command failed with exit code 1:
.zig-cache/o/9fc7ed28134f4e2db1c74dd2fec2d80c/build /usr/bin/zig /usr/lib/zig /home/dwilliams/.cache/yay/oxwm-git/src/oxwm .zig-cache /home/dwilliams/.cache/zig --seed 0x810c1ca4 -Z2a06ba5d3cde19b1 test -Doptimize=ReleaseSmall
==> ERROR: A failure occurred in check().
    Aborting...
 -> error making: oxwm-git-exit status 4
 -> Failed to install the following packages. Manual intervention is required:
oxwm-git - exit status 4

zig version
0.15.2

 On branch ddubs-config
 Your branch is up to date with 'origin/ddubs-config'.

 Changes to be committed:
	modified:   build.zig
	new file:   resources/oxwm-parser